INSERT INTO evaluadores (cod_evaluador, especialidad_evaluador, cod_institucion, cod_usuario, nombre1, nombre2, apellido1, apellido2, telefono1, telefono2, genero, correo_electronico) VALUES
(1, 'Experto en Bases de Datos', 1, 7, 'Martina', 'Lucía', 'Benavides', 'Ríos', '3011112233', NULL, 'F', 'martina.benavides@evaluador.com'),
(2, 'Especialista en IA y Machine Learning', 2, 19, 'Esteban', 'Gabriel', 'Quintana', 'Luna', '3012223344', NULL, 'M', 'esteban.quintana@evaluador.com'),
(3, 'Consultor de Proyectos de Software', 2, 1, 'Sofía', 'Eugenia', 'Montes', 'Pinto', '3013334455', NULL, 'F', 'sofia.montes@evaluador.com'),
(4, 'Metodólogo de Investigación', 1, 13, 'Alejandro', 'Daniel', 'Salazar', 'Mora', '3014445566', NULL, 'M', 'alejandro.salazar@evaluador.com'),
(5, 'Experto en Diseño UI/UX', 3, 15, 'Valentina', 'Andrea', 'Gutiérrez', 'Bravo', '3015556677', NULL, 'F', 'valentina.gutierrez@evaluador.com'),
(6, 'Experto en Seguridad Informática', 1, 96, 'Daniel', 'José', 'Vargas', 'Rojas', '3011233001', NULL, 'M', 'daniel.vargas@evaluador.com'),
(7, 'Especialista en Big Data', 2, 97, 'Lucía', 'Fernanda', 'Paredes', 'Soto', '3011233002', NULL, 'F', 'lucia.paredes@evaluador.com'),
(8, 'Consultor de Gestión de Proyectos', 3, 98, 'Roberto', 'Carlos', 'Molina', 'Vega', '3011233003', NULL, 'M', 'roberto.molina@evaluador.com'),
(9, 'Investigador de Inteligencia Artificial', 1, 99, 'Sofía', 'Isabel', 'Castañeda', 'Lara', '3011233004', NULL, 'F', 'sofia.castaneda@evaluador.com'),
(10, 'Experto en Desarrollo Web', 2, 100, 'Pablo', 'Andrés', 'Guerrero', 'Ortiz', '3011233005', NULL, 'M', 'pablo.guerrero@evaluador.com'),
(11, 'Consultor de Proyectos Educativos', 1, 91, 'Carolina', 'Isabel', 'Díaz', 'Martínez', '3011230011', NULL, 'F', 'carolina.diaz@evaluador.com'),
(12, 'Ingeniero Ambiental', 3, 92, 'Luis', 'Alberto', 'Fernández', 'Ramírez', '3011230012', NULL, 'M', 'luis.fernandez@evaluador.com'),
(13, 'Diseñador Industrial', 1, 93, 'María', 'Fernanda', 'Sánchez', 'Vargas', '3011230013', NULL, 'F', 'maria.sanchez@evaluador.com'),
(14, 'Desarrollador Web Fullstack', 2, 94, 'Sergio', 'Mauricio', 'Torres', 'Benítez', '3011230014', NULL, 'M', 'sergio.torres@evaluador.com'),
(15, 'Especialista en Marketing Digital', 3, 95, 'Andrea', 'Carolina', 'Herrera', 'Quintero', '3011230015', NULL, 'F', 'andrea.herrera@evaluador.com');